# 数据源信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3333/spring_cache
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 启用 Redis
  redis:
    host: localhost

# 开启驼峰命名...
mybatis:
  configuration:
    map-underscore-to-camel-case: true

debug: true